### ISSUE TITLE
NumPad container

### ISSUE THREAD

**Issue by esauri** [GoodHombres/TipTap#10]
Create a ```NumPad``` container component for the lower half of the calculator view.

Props that shall be passed down from ```Calculator``` to ```NumPad```:
* ```this.state.amountEntered```
* ```this.handleNavigation```
* Methods that need to be created for **adding**, **subtracting**, and/or **clearing** the ```amountEntered``` in state.

Must contain buttons for **Clear**, **Delete**, **Camera**, and numerical **0-9**. Add *00* if you'd like.

The Camera button should be disabled for now.
The other buttons should call a method for **adding**, **subtracting**, or **clearing** the ```amountEntered``` in state.
If ```amountEntered``` is empty then the **Clear** and **Delete** buttons should be disabled.

Must also contain a **Calculate** button that calls ```Calculator```'s ```handleNavigation()```.  The route should be ```null``` for now but the param should be the ```amountEntered```.

**Comment by esauri** [comment]
NumPad container has a ```backgroundColor: 'rgba(246, 247, 249, 0.08)'```

**Comment by cmedinasoriano1** [comment]
Closed via #13
