### ISSUE TITLE
Favorite Tips not being updated on Calculator

### ISSUE THREAD

**Issue by cmedinasoriano1** [GoodHombres/TipTap#30]
Settings change to favorites are not reflected in Calculator view immediately.  App must be reloaded to update favorites list in Calculator view.  App should reflect immediately any update to the settings.

To replicate:
Navigate to Settings -> Add a new tip -> Mark this tip as favorite -> Navigate back to Calculator

**Comment by esauri** [comment]
Blocked by #28
