### ISSUE TITLE
Request: Save settings on demand to enhance user experience (Usability)

### ISSUE THREAD

**Issue by cmedinasoriano1** [GoodHombres/TipTap#31]
An undesired side effect for the user can be caused by not saving setting variables to local storage when a change is done. Currently, all changes will be lost if user closes app, or app crashes, before componentWillUnmount is called. 

I suggest to store changes as they are done to the local storage, sacrificing a little bit of performance for user experience.  Since local storing work is done asynchronously by AsyncStorage, every change will be stacked and executed in order as it was performed by the user but will not halt the application.

**Comment by esauri** [comment]
👍🏽
